export const entities = [
    'report', 
    'scenario',
    'problem',
    'solution',
    'observation',
    'trend'
]
export const topics = [
    'Geoengineering', 
    'Democratization',
    'Decisioning for EcoSystem Wellness'
]
export const ilities = [
    "accessibility",
    "accountability",
    "accuracy",
    "adaptability",
    "administrability",
    "affordability",
    "auditability",
    "availability",
    "compatibility",
    "confidentiality",
    "configurability",
    "durability",
    "effectiveness",
    "efficiency",
    "evolvability",
    "extensibility",
    "failure transparency",
    "fault-tolerance",
    "fidelity",
    "flexibility",
    "inspectability",
    "installability",
    "interoperability",
    "learnability",
    "localizability",
    "maintainability",
    "manageability",
    "mobility",
    "modifiability",
    "portability",
    "predictability",
    "reliability",
    "repeatability",
    "reusability",
    "safety",
    "scalability",
    "self-sustainability",
    "stability",
    "survivability",
    "sustainability",
    "tailorability",
    "testability",
    "timeliness",
    "traceability",
    "transparency",
    "ubiquity",
    "understandability",
    "upgradability",
    "usability"
];


export const needs = [
    "- BIOLOGICAL NEED",
    "air",
    "food",
    "water",
    "sleep",
    "warmth",
    "sexual expression",
    "- SAFETY NEED",
    "shelter",
    "safety",
    "security",
    "stability/peace",
    "law and order",
    "- PSYCHOLOGICAL NEED",
    "intimacy",
    "joy",
    "play",
    "inspiration",
    "companionship",
    "communication",
    "trust",
    "appreciation",
    "compassion",
    "empathy",
    "respect",
    "- COMMUNAL NEED",
    "equality",
    "belonging",
    "community",
    "cooperation",
    "support",
    "mourning",
    "- AUTONOMY",
    "choice",
    "freedom",
    "independence",
    "space",
    "spontaneity",
    "- ESTEEM NEED",
    "dignity",
    "achievement",
    "status",
    "prestige",
    "- COGNITIVE NEED",
    "competence",
    "contribution",
    "creativity",
    "discovery",
    "growth",
    "hope",
    "learning",
    "purpose",
    "self-expression",
];


export const categories = [
    "Agriculture, Forestry, Fishing and Hunting",
    "Mining, Quarrying, and Oil and Gas Extraction",
    "Utilities",
    "Construction",
    "Manufacturing",
    "Wholesale Trade",
    "Retail Trade",
    "Transportation and Warehousing",
    "Information",
    "Finance and Insurance",
    "Real Estate and Rental and Leasing",
    "Professional, Scientific, and Technical Services",
    "Management of Companies and Enterprises",
    "Administrative and Support and Waste Management and Remediation Services",
    "Educational Services",
    "Health Care and Social Assistance",
    "Arts, Entertainment, and Recreation",
    "Accommodation and Food Services",
    "Other Services (except Public Administration)",
    "Public Administration"
];
export const subcategories = [
    "Oilseed and Grain Farming",
    "Soybean Farming",
    "Oilseed (except Soybean) Farming",
    "Dry Pea and Bean Farming",
    "Wheat Farming",
    "Corn Farming",
    "Rice Farming",
    "Oilseed and Grain Combination Farming",
    "All Other Grain Farming",
    "Vegetable and Melon Farming",
    "Potato Farming",
    "Other Vegetable (except Potato) and Melon Farming",
    "Fruit and Tree Nut Farming",
    "Orange Groves",
    "Citrus (except Orange) Groves",
    "Apple Orchards",
    "Grape Vineyards",
    "Strawberry Farming",
    "Berry (except Strawberry) Farming",
    "Tree Nut Farming",
    "Fruit and Tree Nut Combination Farming",
    "Other Noncitrus Fruit Farming",
    "Greenhouse, Nursery, and Floriculture Production",
    "Mushroom Production",
    "Other Food Crops Grown Under Cover",
    "Nursery and Tree Production",
    "Floriculture Production",
    "Other Crop Farming",
    "Tobacco Farming",
    "Cotton Farming",
    "Sugarcane Farming",
    "Hay Farming",
    "Sugar Beet Farming",
    "Peanut Farming",
    "All Other Miscellaneous Crop Farming",
    "Cattle Ranching and Farming",
    "Beef Cattle Ranching and Farming",
    "Cattle Feedlots",
    "Dairy Cattle and Milk Production",
    "Dual-Purpose Cattle Ranching and Farming",
    "Hog and Pig Farming",
    "Poultry and Egg Production",
    "Chicken Egg Production",
    "Broilers and Other Meat Type Chicken Production",
    "Turkey Production",
    "Poultry Hatcheries",
    "Other Poultry Production",
    "Sheep and Goat Farming",
    "Sheep Farming",
    "Goat Farming",
    "Aquaculture",
    "Finfish Farming and Fish Hatcheries",
    "Shellfish Farming",
    "Other Aquaculture",
    "Other Animal Production",
    "Apiculture",
    "Horses and Other Equine Production",
    "Fur-Bearing Animal and Rabbit Production",
    "All Other Animal Production",
];